/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PumaRouteImport } from './routes/puma'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignIndexRouteImport } from './routes/campaign/index'
import { Route as PumaRevenueGrossPrabayarRouteImport } from './routes/puma/revenue-gross-prabayar'
import { Route as PumaRevenueGrossRouteImport } from './routes/puma/revenue-gross'
import { Route as PumaRevenueByuRouteImport } from './routes/puma/revenue-byu'
import { Route as HouseholdSalesFulfilmentRouteImport } from './routes/household/sales-fulfilment'
import { Route as HouseholdRevenueC3mrRouteImport } from './routes/household/revenue-c3mr'
import { Route as HouseholdDemandsDeploymentRouteImport } from './routes/household/demands-deployment'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoDbChatApiRouteImport } from './routes/demo/db-chat-api'
import { Route as DemoDbChatRouteImport } from './routes/demo/db-chat'
import { Route as CampaignAchievementRouteImport } from './routes/campaign/achievement'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const PumaRoute = PumaRouteImport.update({
  id: '/puma',
  path: '/puma',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIndexRoute = CampaignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignRoute,
} as any)
const PumaRevenueGrossPrabayarRoute =
  PumaRevenueGrossPrabayarRouteImport.update({
    id: '/revenue-gross-prabayar',
    path: '/revenue-gross-prabayar',
    getParentRoute: () => PumaRoute,
  } as any)
const PumaRevenueGrossRoute = PumaRevenueGrossRouteImport.update({
  id: '/revenue-gross',
  path: '/revenue-gross',
  getParentRoute: () => PumaRoute,
} as any)
const PumaRevenueByuRoute = PumaRevenueByuRouteImport.update({
  id: '/revenue-byu',
  path: '/revenue-byu',
  getParentRoute: () => PumaRoute,
} as any)
const HouseholdSalesFulfilmentRoute =
  HouseholdSalesFulfilmentRouteImport.update({
    id: '/sales-fulfilment',
    path: '/sales-fulfilment',
    getParentRoute: () => HouseholdRoute,
  } as any)
const HouseholdRevenueC3mrRoute = HouseholdRevenueC3mrRouteImport.update({
  id: '/revenue-c3mr',
  path: '/revenue-c3mr',
  getParentRoute: () => HouseholdRoute,
} as any)
const HouseholdDemandsDeploymentRoute =
  HouseholdDemandsDeploymentRouteImport.update({
    id: '/demands-deployment',
    path: '/demands-deployment',
    getParentRoute: () => HouseholdRoute,
  } as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatApiRoute = DemoDbChatApiRouteImport.update({
  id: '/demo/db-chat-api',
  path: '/demo/db-chat-api',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatRoute = DemoDbChatRouteImport.update({
  id: '/demo/db-chat',
  path: '/demo/db-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignAchievementRoute = CampaignAchievementRouteImport.update({
  id: '/achievement',
  path: '/achievement',
  getParentRoute: () => CampaignRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteWithChildren
  '/household': typeof HouseholdRouteWithChildren
  '/login': typeof LoginRoute
  '/puma': typeof PumaRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/campaign/achievement': typeof CampaignAchievementRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/household/demands-deployment': typeof HouseholdDemandsDeploymentRoute
  '/household/revenue-c3mr': typeof HouseholdRevenueC3mrRoute
  '/household/sales-fulfilment': typeof HouseholdSalesFulfilmentRoute
  '/puma/revenue-byu': typeof PumaRevenueByuRoute
  '/puma/revenue-gross': typeof PumaRevenueGrossRoute
  '/puma/revenue-gross-prabayar': typeof PumaRevenueGrossPrabayarRoute
  '/campaign/': typeof CampaignIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/household': typeof HouseholdRouteWithChildren
  '/login': typeof LoginRoute
  '/puma': typeof PumaRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/campaign/achievement': typeof CampaignAchievementRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/household/demands-deployment': typeof HouseholdDemandsDeploymentRoute
  '/household/revenue-c3mr': typeof HouseholdRevenueC3mrRoute
  '/household/sales-fulfilment': typeof HouseholdSalesFulfilmentRoute
  '/puma/revenue-byu': typeof PumaRevenueByuRoute
  '/puma/revenue-gross': typeof PumaRevenueGrossRoute
  '/puma/revenue-gross-prabayar': typeof PumaRevenueGrossPrabayarRoute
  '/campaign': typeof CampaignIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteWithChildren
  '/household': typeof HouseholdRouteWithChildren
  '/login': typeof LoginRoute
  '/puma': typeof PumaRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/campaign/achievement': typeof CampaignAchievementRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/household/demands-deployment': typeof HouseholdDemandsDeploymentRoute
  '/household/revenue-c3mr': typeof HouseholdRevenueC3mrRoute
  '/household/sales-fulfilment': typeof HouseholdSalesFulfilmentRoute
  '/puma/revenue-byu': typeof PumaRevenueByuRoute
  '/puma/revenue-gross': typeof PumaRevenueGrossRoute
  '/puma/revenue-gross-prabayar': typeof PumaRevenueGrossPrabayarRoute
  '/campaign/': typeof CampaignIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaign'
    | '/household'
    | '/login'
    | '/puma'
    | '/api/$'
    | '/campaign/achievement'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/household/demands-deployment'
    | '/household/revenue-c3mr'
    | '/household/sales-fulfilment'
    | '/puma/revenue-byu'
    | '/puma/revenue-gross'
    | '/puma/revenue-gross-prabayar'
    | '/campaign/'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/household'
    | '/login'
    | '/puma'
    | '/api/$'
    | '/campaign/achievement'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/household/demands-deployment'
    | '/household/revenue-c3mr'
    | '/household/sales-fulfilment'
    | '/puma/revenue-byu'
    | '/puma/revenue-gross'
    | '/puma/revenue-gross-prabayar'
    | '/campaign'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/campaign'
    | '/household'
    | '/login'
    | '/puma'
    | '/api/$'
    | '/campaign/achievement'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/household/demands-deployment'
    | '/household/revenue-c3mr'
    | '/household/sales-fulfilment'
    | '/puma/revenue-byu'
    | '/puma/revenue-gross'
    | '/puma/revenue-gross-prabayar'
    | '/campaign/'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignRoute: typeof CampaignRouteWithChildren
  HouseholdRoute: typeof HouseholdRouteWithChildren
  LoginRoute: typeof LoginRoute
  PumaRoute: typeof PumaRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  DemoDbChatRoute: typeof DemoDbChatRoute
  DemoDbChatApiRoute: typeof DemoDbChatApiRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/puma': {
      id: '/puma'
      path: '/puma'
      fullPath: '/puma'
      preLoaderRoute: typeof PumaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/': {
      id: '/campaign/'
      path: '/'
      fullPath: '/campaign/'
      preLoaderRoute: typeof CampaignIndexRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/puma/revenue-gross-prabayar': {
      id: '/puma/revenue-gross-prabayar'
      path: '/revenue-gross-prabayar'
      fullPath: '/puma/revenue-gross-prabayar'
      preLoaderRoute: typeof PumaRevenueGrossPrabayarRouteImport
      parentRoute: typeof PumaRoute
    }
    '/puma/revenue-gross': {
      id: '/puma/revenue-gross'
      path: '/revenue-gross'
      fullPath: '/puma/revenue-gross'
      preLoaderRoute: typeof PumaRevenueGrossRouteImport
      parentRoute: typeof PumaRoute
    }
    '/puma/revenue-byu': {
      id: '/puma/revenue-byu'
      path: '/revenue-byu'
      fullPath: '/puma/revenue-byu'
      preLoaderRoute: typeof PumaRevenueByuRouteImport
      parentRoute: typeof PumaRoute
    }
    '/household/sales-fulfilment': {
      id: '/household/sales-fulfilment'
      path: '/sales-fulfilment'
      fullPath: '/household/sales-fulfilment'
      preLoaderRoute: typeof HouseholdSalesFulfilmentRouteImport
      parentRoute: typeof HouseholdRoute
    }
    '/household/revenue-c3mr': {
      id: '/household/revenue-c3mr'
      path: '/revenue-c3mr'
      fullPath: '/household/revenue-c3mr'
      preLoaderRoute: typeof HouseholdRevenueC3mrRouteImport
      parentRoute: typeof HouseholdRoute
    }
    '/household/demands-deployment': {
      id: '/household/demands-deployment'
      path: '/demands-deployment'
      fullPath: '/household/demands-deployment'
      preLoaderRoute: typeof HouseholdDemandsDeploymentRouteImport
      parentRoute: typeof HouseholdRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat-api': {
      id: '/demo/db-chat-api'
      path: '/demo/db-chat-api'
      fullPath: '/demo/db-chat-api'
      preLoaderRoute: typeof DemoDbChatApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat': {
      id: '/demo/db-chat'
      path: '/demo/db-chat'
      fullPath: '/demo/db-chat'
      preLoaderRoute: typeof DemoDbChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/achievement': {
      id: '/campaign/achievement'
      path: '/achievement'
      fullPath: '/campaign/achievement'
      preLoaderRoute: typeof CampaignAchievementRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CampaignRouteChildren {
  CampaignAchievementRoute: typeof CampaignAchievementRoute
  CampaignIndexRoute: typeof CampaignIndexRoute
}

const CampaignRouteChildren: CampaignRouteChildren = {
  CampaignAchievementRoute: CampaignAchievementRoute,
  CampaignIndexRoute: CampaignIndexRoute,
}

const CampaignRouteWithChildren = CampaignRoute._addFileChildren(
  CampaignRouteChildren,
)

interface HouseholdRouteChildren {
  HouseholdDemandsDeploymentRoute: typeof HouseholdDemandsDeploymentRoute
  HouseholdRevenueC3mrRoute: typeof HouseholdRevenueC3mrRoute
  HouseholdSalesFulfilmentRoute: typeof HouseholdSalesFulfilmentRoute
}

const HouseholdRouteChildren: HouseholdRouteChildren = {
  HouseholdDemandsDeploymentRoute: HouseholdDemandsDeploymentRoute,
  HouseholdRevenueC3mrRoute: HouseholdRevenueC3mrRoute,
  HouseholdSalesFulfilmentRoute: HouseholdSalesFulfilmentRoute,
}

const HouseholdRouteWithChildren = HouseholdRoute._addFileChildren(
  HouseholdRouteChildren,
)

interface PumaRouteChildren {
  PumaRevenueByuRoute: typeof PumaRevenueByuRoute
  PumaRevenueGrossRoute: typeof PumaRevenueGrossRoute
  PumaRevenueGrossPrabayarRoute: typeof PumaRevenueGrossPrabayarRoute
}

const PumaRouteChildren: PumaRouteChildren = {
  PumaRevenueByuRoute: PumaRevenueByuRoute,
  PumaRevenueGrossRoute: PumaRevenueGrossRoute,
  PumaRevenueGrossPrabayarRoute: PumaRevenueGrossPrabayarRoute,
}

const PumaRouteWithChildren = PumaRoute._addFileChildren(PumaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignRoute: CampaignRouteWithChildren,
  HouseholdRoute: HouseholdRouteWithChildren,
  LoginRoute: LoginRoute,
  PumaRoute: PumaRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  DemoDbChatRoute: DemoDbChatRoute,
  DemoDbChatApiRoute: DemoDbChatApiRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
