/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PumaRouteImport } from './routes/puma'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignIndexRouteImport } from './routes/campaign/index'
import { Route as PumaTrxNewSalesPrabayarRouteImport } from './routes/puma/trx-new-sales-prabayar'
import { Route as PumaTrxNewSalesByuRouteImport } from './routes/puma/trx-new-sales-byu'
import { Route as PumaTrxNewSalesRouteImport } from './routes/puma/trx-new-sales'
import { Route as PumaTargetSoRouteImport } from './routes/puma/target-so'
import { Route as PumaRevenueRedeemPvRouteImport } from './routes/puma/revenue-redeem-pv'
import { Route as PumaRevenueNewSalesPrabayarRouteImport } from './routes/puma/revenue-new-sales-prabayar'
import { Route as PumaRevenueNewSalesRouteImport } from './routes/puma/revenue-new-sales'
import { Route as PumaRevenueGrossPrabayarRouteImport } from './routes/puma/revenue-gross-prabayar'
import { Route as PumaRevenueGrossRouteImport } from './routes/puma/revenue-gross'
import { Route as PumaRevenueCvmOutletRouteImport } from './routes/puma/revenue-cvm-outlet'
import { Route as PumaRevenueCvmRouteImport } from './routes/puma/revenue-cvm'
import { Route as PumaRevenueByuRouteImport } from './routes/puma/revenue-byu'
import { Route as PumaPayingSubsRouteImport } from './routes/puma/paying-subs'
import { Route as HouseholdSalesFulfilmentRouteImport } from './routes/household/sales-fulfilment'
import { Route as HouseholdRevenueC3mrRouteImport } from './routes/household/revenue-c3mr'
import { Route as HouseholdDemandsDeploymentRouteImport } from './routes/household/demands-deployment'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as HouseholdConsolidationMobileHhRouteRouteImport } from './routes/household/consolidation-mobile-hh/route'
import { Route as HouseholdConsolidationMobileHhRevBbRouteImport } from './routes/household/consolidation-mobile-hh/rev-bb'
import { Route as HouseholdConsolidationMobileHhRevAllRouteImport } from './routes/household/consolidation-mobile-hh/rev-all'
import { Route as HouseholdConsolidationMobileHhPayloadRouteImport } from './routes/household/consolidation-mobile-hh/payload'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PumaRoute = PumaRouteImport.update({
  id: '/puma',
  path: '/puma',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIndexRoute = CampaignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignRoute,
} as any)
const PumaTrxNewSalesPrabayarRoute = PumaTrxNewSalesPrabayarRouteImport.update({
  id: '/trx-new-sales-prabayar',
  path: '/trx-new-sales-prabayar',
  getParentRoute: () => PumaRoute,
} as any)
const PumaTrxNewSalesByuRoute = PumaTrxNewSalesByuRouteImport.update({
  id: '/trx-new-sales-byu',
  path: '/trx-new-sales-byu',
  getParentRoute: () => PumaRoute,
} as any)
const PumaTrxNewSalesRoute = PumaTrxNewSalesRouteImport.update({
  id: '/trx-new-sales',
  path: '/trx-new-sales',
  getParentRoute: () => PumaRoute,
} as any)
const PumaTargetSoRoute = PumaTargetSoRouteImport.update({
  id: '/target-so',
  path: '/target-so',
  getParentRoute: () => PumaRoute,
} as any)
const PumaRevenueRedeemPvRoute = PumaRevenueRedeemPvRouteImport.update({
  id: '/revenue-redeem-pv',
  path: '/revenue-redeem-pv',
  getParentRoute: () => PumaRoute,
} as any)
const PumaRevenueNewSalesPrabayarRoute =
  PumaRevenueNewSalesPrabayarRouteImport.update({
    id: '/revenue-new-sales-prabayar',
    path: '/revenue-new-sales-prabayar',
    getParentRoute: () => PumaRoute,
  } as any)
const PumaRevenueNewSalesRoute = PumaRevenueNewSalesRouteImport.update({
  id: '/revenue-new-sales',
  path: '/revenue-new-sales',
  getParentRoute: () => PumaRoute,
} as any)
const PumaRevenueGrossPrabayarRoute =
  PumaRevenueGrossPrabayarRouteImport.update({
    id: '/revenue-gross-prabayar',
    path: '/revenue-gross-prabayar',
    getParentRoute: () => PumaRoute,
  } as any)
const PumaRevenueGrossRoute = PumaRevenueGrossRouteImport.update({
  id: '/revenue-gross',
  path: '/revenue-gross',
  getParentRoute: () => PumaRoute,
} as any)
const PumaRevenueCvmOutletRoute = PumaRevenueCvmOutletRouteImport.update({
  id: '/revenue-cvm-outlet',
  path: '/revenue-cvm-outlet',
  getParentRoute: () => PumaRoute,
} as any)
const PumaRevenueCvmRoute = PumaRevenueCvmRouteImport.update({
  id: '/revenue-cvm',
  path: '/revenue-cvm',
  getParentRoute: () => PumaRoute,
} as any)
const PumaRevenueByuRoute = PumaRevenueByuRouteImport.update({
  id: '/revenue-byu',
  path: '/revenue-byu',
  getParentRoute: () => PumaRoute,
} as any)
const PumaPayingSubsRoute = PumaPayingSubsRouteImport.update({
  id: '/paying-subs',
  path: '/paying-subs',
  getParentRoute: () => PumaRoute,
} as any)
const HouseholdSalesFulfilmentRoute =
  HouseholdSalesFulfilmentRouteImport.update({
    id: '/sales-fulfilment',
    path: '/sales-fulfilment',
    getParentRoute: () => HouseholdRoute,
  } as any)
const HouseholdRevenueC3mrRoute = HouseholdRevenueC3mrRouteImport.update({
  id: '/revenue-c3mr',
  path: '/revenue-c3mr',
  getParentRoute: () => HouseholdRoute,
} as any)
const HouseholdDemandsDeploymentRoute =
  HouseholdDemandsDeploymentRouteImport.update({
    id: '/demands-deployment',
    path: '/demands-deployment',
    getParentRoute: () => HouseholdRoute,
  } as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdConsolidationMobileHhRouteRoute =
  HouseholdConsolidationMobileHhRouteRouteImport.update({
    id: '/consolidation-mobile-hh',
    path: '/consolidation-mobile-hh',
    getParentRoute: () => HouseholdRoute,
  } as any)
const HouseholdConsolidationMobileHhRevBbRoute =
  HouseholdConsolidationMobileHhRevBbRouteImport.update({
    id: '/rev-bb',
    path: '/rev-bb',
    getParentRoute: () => HouseholdConsolidationMobileHhRouteRoute,
  } as any)
const HouseholdConsolidationMobileHhRevAllRoute =
  HouseholdConsolidationMobileHhRevAllRouteImport.update({
    id: '/rev-all',
    path: '/rev-all',
    getParentRoute: () => HouseholdConsolidationMobileHhRouteRoute,
  } as any)
const HouseholdConsolidationMobileHhPayloadRoute =
  HouseholdConsolidationMobileHhPayloadRouteImport.update({
    id: '/payload',
    path: '/payload',
    getParentRoute: () => HouseholdConsolidationMobileHhRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteWithChildren
  '/household': typeof HouseholdRouteWithChildren
  '/login': typeof LoginRoute
  '/puma': typeof PumaRouteWithChildren
  '/register': typeof RegisterRoute
  '/household/consolidation-mobile-hh': typeof HouseholdConsolidationMobileHhRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/household/demands-deployment': typeof HouseholdDemandsDeploymentRoute
  '/household/revenue-c3mr': typeof HouseholdRevenueC3mrRoute
  '/household/sales-fulfilment': typeof HouseholdSalesFulfilmentRoute
  '/puma/paying-subs': typeof PumaPayingSubsRoute
  '/puma/revenue-byu': typeof PumaRevenueByuRoute
  '/puma/revenue-cvm': typeof PumaRevenueCvmRoute
  '/puma/revenue-cvm-outlet': typeof PumaRevenueCvmOutletRoute
  '/puma/revenue-gross': typeof PumaRevenueGrossRoute
  '/puma/revenue-gross-prabayar': typeof PumaRevenueGrossPrabayarRoute
  '/puma/revenue-new-sales': typeof PumaRevenueNewSalesRoute
  '/puma/revenue-new-sales-prabayar': typeof PumaRevenueNewSalesPrabayarRoute
  '/puma/revenue-redeem-pv': typeof PumaRevenueRedeemPvRoute
  '/puma/target-so': typeof PumaTargetSoRoute
  '/puma/trx-new-sales': typeof PumaTrxNewSalesRoute
  '/puma/trx-new-sales-byu': typeof PumaTrxNewSalesByuRoute
  '/puma/trx-new-sales-prabayar': typeof PumaTrxNewSalesPrabayarRoute
  '/campaign/': typeof CampaignIndexRoute
  '/household/consolidation-mobile-hh/payload': typeof HouseholdConsolidationMobileHhPayloadRoute
  '/household/consolidation-mobile-hh/rev-all': typeof HouseholdConsolidationMobileHhRevAllRoute
  '/household/consolidation-mobile-hh/rev-bb': typeof HouseholdConsolidationMobileHhRevBbRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/household': typeof HouseholdRouteWithChildren
  '/login': typeof LoginRoute
  '/puma': typeof PumaRouteWithChildren
  '/register': typeof RegisterRoute
  '/household/consolidation-mobile-hh': typeof HouseholdConsolidationMobileHhRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/household/demands-deployment': typeof HouseholdDemandsDeploymentRoute
  '/household/revenue-c3mr': typeof HouseholdRevenueC3mrRoute
  '/household/sales-fulfilment': typeof HouseholdSalesFulfilmentRoute
  '/puma/paying-subs': typeof PumaPayingSubsRoute
  '/puma/revenue-byu': typeof PumaRevenueByuRoute
  '/puma/revenue-cvm': typeof PumaRevenueCvmRoute
  '/puma/revenue-cvm-outlet': typeof PumaRevenueCvmOutletRoute
  '/puma/revenue-gross': typeof PumaRevenueGrossRoute
  '/puma/revenue-gross-prabayar': typeof PumaRevenueGrossPrabayarRoute
  '/puma/revenue-new-sales': typeof PumaRevenueNewSalesRoute
  '/puma/revenue-new-sales-prabayar': typeof PumaRevenueNewSalesPrabayarRoute
  '/puma/revenue-redeem-pv': typeof PumaRevenueRedeemPvRoute
  '/puma/target-so': typeof PumaTargetSoRoute
  '/puma/trx-new-sales': typeof PumaTrxNewSalesRoute
  '/puma/trx-new-sales-byu': typeof PumaTrxNewSalesByuRoute
  '/puma/trx-new-sales-prabayar': typeof PumaTrxNewSalesPrabayarRoute
  '/campaign': typeof CampaignIndexRoute
  '/household/consolidation-mobile-hh/payload': typeof HouseholdConsolidationMobileHhPayloadRoute
  '/household/consolidation-mobile-hh/rev-all': typeof HouseholdConsolidationMobileHhRevAllRoute
  '/household/consolidation-mobile-hh/rev-bb': typeof HouseholdConsolidationMobileHhRevBbRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteWithChildren
  '/household': typeof HouseholdRouteWithChildren
  '/login': typeof LoginRoute
  '/puma': typeof PumaRouteWithChildren
  '/register': typeof RegisterRoute
  '/household/consolidation-mobile-hh': typeof HouseholdConsolidationMobileHhRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/household/demands-deployment': typeof HouseholdDemandsDeploymentRoute
  '/household/revenue-c3mr': typeof HouseholdRevenueC3mrRoute
  '/household/sales-fulfilment': typeof HouseholdSalesFulfilmentRoute
  '/puma/paying-subs': typeof PumaPayingSubsRoute
  '/puma/revenue-byu': typeof PumaRevenueByuRoute
  '/puma/revenue-cvm': typeof PumaRevenueCvmRoute
  '/puma/revenue-cvm-outlet': typeof PumaRevenueCvmOutletRoute
  '/puma/revenue-gross': typeof PumaRevenueGrossRoute
  '/puma/revenue-gross-prabayar': typeof PumaRevenueGrossPrabayarRoute
  '/puma/revenue-new-sales': typeof PumaRevenueNewSalesRoute
  '/puma/revenue-new-sales-prabayar': typeof PumaRevenueNewSalesPrabayarRoute
  '/puma/revenue-redeem-pv': typeof PumaRevenueRedeemPvRoute
  '/puma/target-so': typeof PumaTargetSoRoute
  '/puma/trx-new-sales': typeof PumaTrxNewSalesRoute
  '/puma/trx-new-sales-byu': typeof PumaTrxNewSalesByuRoute
  '/puma/trx-new-sales-prabayar': typeof PumaTrxNewSalesPrabayarRoute
  '/campaign/': typeof CampaignIndexRoute
  '/household/consolidation-mobile-hh/payload': typeof HouseholdConsolidationMobileHhPayloadRoute
  '/household/consolidation-mobile-hh/rev-all': typeof HouseholdConsolidationMobileHhRevAllRoute
  '/household/consolidation-mobile-hh/rev-bb': typeof HouseholdConsolidationMobileHhRevBbRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaign'
    | '/household'
    | '/login'
    | '/puma'
    | '/register'
    | '/household/consolidation-mobile-hh'
    | '/api/$'
    | '/household/demands-deployment'
    | '/household/revenue-c3mr'
    | '/household/sales-fulfilment'
    | '/puma/paying-subs'
    | '/puma/revenue-byu'
    | '/puma/revenue-cvm'
    | '/puma/revenue-cvm-outlet'
    | '/puma/revenue-gross'
    | '/puma/revenue-gross-prabayar'
    | '/puma/revenue-new-sales'
    | '/puma/revenue-new-sales-prabayar'
    | '/puma/revenue-redeem-pv'
    | '/puma/target-so'
    | '/puma/trx-new-sales'
    | '/puma/trx-new-sales-byu'
    | '/puma/trx-new-sales-prabayar'
    | '/campaign/'
    | '/household/consolidation-mobile-hh/payload'
    | '/household/consolidation-mobile-hh/rev-all'
    | '/household/consolidation-mobile-hh/rev-bb'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/household'
    | '/login'
    | '/puma'
    | '/register'
    | '/household/consolidation-mobile-hh'
    | '/api/$'
    | '/household/demands-deployment'
    | '/household/revenue-c3mr'
    | '/household/sales-fulfilment'
    | '/puma/paying-subs'
    | '/puma/revenue-byu'
    | '/puma/revenue-cvm'
    | '/puma/revenue-cvm-outlet'
    | '/puma/revenue-gross'
    | '/puma/revenue-gross-prabayar'
    | '/puma/revenue-new-sales'
    | '/puma/revenue-new-sales-prabayar'
    | '/puma/revenue-redeem-pv'
    | '/puma/target-so'
    | '/puma/trx-new-sales'
    | '/puma/trx-new-sales-byu'
    | '/puma/trx-new-sales-prabayar'
    | '/campaign'
    | '/household/consolidation-mobile-hh/payload'
    | '/household/consolidation-mobile-hh/rev-all'
    | '/household/consolidation-mobile-hh/rev-bb'
  id:
    | '__root__'
    | '/'
    | '/campaign'
    | '/household'
    | '/login'
    | '/puma'
    | '/register'
    | '/household/consolidation-mobile-hh'
    | '/api/$'
    | '/household/demands-deployment'
    | '/household/revenue-c3mr'
    | '/household/sales-fulfilment'
    | '/puma/paying-subs'
    | '/puma/revenue-byu'
    | '/puma/revenue-cvm'
    | '/puma/revenue-cvm-outlet'
    | '/puma/revenue-gross'
    | '/puma/revenue-gross-prabayar'
    | '/puma/revenue-new-sales'
    | '/puma/revenue-new-sales-prabayar'
    | '/puma/revenue-redeem-pv'
    | '/puma/target-so'
    | '/puma/trx-new-sales'
    | '/puma/trx-new-sales-byu'
    | '/puma/trx-new-sales-prabayar'
    | '/campaign/'
    | '/household/consolidation-mobile-hh/payload'
    | '/household/consolidation-mobile-hh/rev-all'
    | '/household/consolidation-mobile-hh/rev-bb'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignRoute: typeof CampaignRouteWithChildren
  HouseholdRoute: typeof HouseholdRouteWithChildren
  LoginRoute: typeof LoginRoute
  PumaRoute: typeof PumaRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puma': {
      id: '/puma'
      path: '/puma'
      fullPath: '/puma'
      preLoaderRoute: typeof PumaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/': {
      id: '/campaign/'
      path: '/'
      fullPath: '/campaign/'
      preLoaderRoute: typeof CampaignIndexRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/puma/trx-new-sales-prabayar': {
      id: '/puma/trx-new-sales-prabayar'
      path: '/trx-new-sales-prabayar'
      fullPath: '/puma/trx-new-sales-prabayar'
      preLoaderRoute: typeof PumaTrxNewSalesPrabayarRouteImport
      parentRoute: typeof PumaRoute
    }
    '/puma/trx-new-sales-byu': {
      id: '/puma/trx-new-sales-byu'
      path: '/trx-new-sales-byu'
      fullPath: '/puma/trx-new-sales-byu'
      preLoaderRoute: typeof PumaTrxNewSalesByuRouteImport
      parentRoute: typeof PumaRoute
    }
    '/puma/trx-new-sales': {
      id: '/puma/trx-new-sales'
      path: '/trx-new-sales'
      fullPath: '/puma/trx-new-sales'
      preLoaderRoute: typeof PumaTrxNewSalesRouteImport
      parentRoute: typeof PumaRoute
    }
    '/puma/target-so': {
      id: '/puma/target-so'
      path: '/target-so'
      fullPath: '/puma/target-so'
      preLoaderRoute: typeof PumaTargetSoRouteImport
      parentRoute: typeof PumaRoute
    }
    '/puma/revenue-redeem-pv': {
      id: '/puma/revenue-redeem-pv'
      path: '/revenue-redeem-pv'
      fullPath: '/puma/revenue-redeem-pv'
      preLoaderRoute: typeof PumaRevenueRedeemPvRouteImport
      parentRoute: typeof PumaRoute
    }
    '/puma/revenue-new-sales-prabayar': {
      id: '/puma/revenue-new-sales-prabayar'
      path: '/revenue-new-sales-prabayar'
      fullPath: '/puma/revenue-new-sales-prabayar'
      preLoaderRoute: typeof PumaRevenueNewSalesPrabayarRouteImport
      parentRoute: typeof PumaRoute
    }
    '/puma/revenue-new-sales': {
      id: '/puma/revenue-new-sales'
      path: '/revenue-new-sales'
      fullPath: '/puma/revenue-new-sales'
      preLoaderRoute: typeof PumaRevenueNewSalesRouteImport
      parentRoute: typeof PumaRoute
    }
    '/puma/revenue-gross-prabayar': {
      id: '/puma/revenue-gross-prabayar'
      path: '/revenue-gross-prabayar'
      fullPath: '/puma/revenue-gross-prabayar'
      preLoaderRoute: typeof PumaRevenueGrossPrabayarRouteImport
      parentRoute: typeof PumaRoute
    }
    '/puma/revenue-gross': {
      id: '/puma/revenue-gross'
      path: '/revenue-gross'
      fullPath: '/puma/revenue-gross'
      preLoaderRoute: typeof PumaRevenueGrossRouteImport
      parentRoute: typeof PumaRoute
    }
    '/puma/revenue-cvm-outlet': {
      id: '/puma/revenue-cvm-outlet'
      path: '/revenue-cvm-outlet'
      fullPath: '/puma/revenue-cvm-outlet'
      preLoaderRoute: typeof PumaRevenueCvmOutletRouteImport
      parentRoute: typeof PumaRoute
    }
    '/puma/revenue-cvm': {
      id: '/puma/revenue-cvm'
      path: '/revenue-cvm'
      fullPath: '/puma/revenue-cvm'
      preLoaderRoute: typeof PumaRevenueCvmRouteImport
      parentRoute: typeof PumaRoute
    }
    '/puma/revenue-byu': {
      id: '/puma/revenue-byu'
      path: '/revenue-byu'
      fullPath: '/puma/revenue-byu'
      preLoaderRoute: typeof PumaRevenueByuRouteImport
      parentRoute: typeof PumaRoute
    }
    '/puma/paying-subs': {
      id: '/puma/paying-subs'
      path: '/paying-subs'
      fullPath: '/puma/paying-subs'
      preLoaderRoute: typeof PumaPayingSubsRouteImport
      parentRoute: typeof PumaRoute
    }
    '/household/sales-fulfilment': {
      id: '/household/sales-fulfilment'
      path: '/sales-fulfilment'
      fullPath: '/household/sales-fulfilment'
      preLoaderRoute: typeof HouseholdSalesFulfilmentRouteImport
      parentRoute: typeof HouseholdRoute
    }
    '/household/revenue-c3mr': {
      id: '/household/revenue-c3mr'
      path: '/revenue-c3mr'
      fullPath: '/household/revenue-c3mr'
      preLoaderRoute: typeof HouseholdRevenueC3mrRouteImport
      parentRoute: typeof HouseholdRoute
    }
    '/household/demands-deployment': {
      id: '/household/demands-deployment'
      path: '/demands-deployment'
      fullPath: '/household/demands-deployment'
      preLoaderRoute: typeof HouseholdDemandsDeploymentRouteImport
      parentRoute: typeof HouseholdRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household/consolidation-mobile-hh': {
      id: '/household/consolidation-mobile-hh'
      path: '/consolidation-mobile-hh'
      fullPath: '/household/consolidation-mobile-hh'
      preLoaderRoute: typeof HouseholdConsolidationMobileHhRouteRouteImport
      parentRoute: typeof HouseholdRoute
    }
    '/household/consolidation-mobile-hh/rev-bb': {
      id: '/household/consolidation-mobile-hh/rev-bb'
      path: '/rev-bb'
      fullPath: '/household/consolidation-mobile-hh/rev-bb'
      preLoaderRoute: typeof HouseholdConsolidationMobileHhRevBbRouteImport
      parentRoute: typeof HouseholdConsolidationMobileHhRouteRoute
    }
    '/household/consolidation-mobile-hh/rev-all': {
      id: '/household/consolidation-mobile-hh/rev-all'
      path: '/rev-all'
      fullPath: '/household/consolidation-mobile-hh/rev-all'
      preLoaderRoute: typeof HouseholdConsolidationMobileHhRevAllRouteImport
      parentRoute: typeof HouseholdConsolidationMobileHhRouteRoute
    }
    '/household/consolidation-mobile-hh/payload': {
      id: '/household/consolidation-mobile-hh/payload'
      path: '/payload'
      fullPath: '/household/consolidation-mobile-hh/payload'
      preLoaderRoute: typeof HouseholdConsolidationMobileHhPayloadRouteImport
      parentRoute: typeof HouseholdConsolidationMobileHhRouteRoute
    }
  }
}

interface CampaignRouteChildren {
  CampaignIndexRoute: typeof CampaignIndexRoute
}

const CampaignRouteChildren: CampaignRouteChildren = {
  CampaignIndexRoute: CampaignIndexRoute,
}

const CampaignRouteWithChildren = CampaignRoute._addFileChildren(
  CampaignRouteChildren,
)

interface HouseholdConsolidationMobileHhRouteRouteChildren {
  HouseholdConsolidationMobileHhPayloadRoute: typeof HouseholdConsolidationMobileHhPayloadRoute
  HouseholdConsolidationMobileHhRevAllRoute: typeof HouseholdConsolidationMobileHhRevAllRoute
  HouseholdConsolidationMobileHhRevBbRoute: typeof HouseholdConsolidationMobileHhRevBbRoute
}

const HouseholdConsolidationMobileHhRouteRouteChildren: HouseholdConsolidationMobileHhRouteRouteChildren =
  {
    HouseholdConsolidationMobileHhPayloadRoute:
      HouseholdConsolidationMobileHhPayloadRoute,
    HouseholdConsolidationMobileHhRevAllRoute:
      HouseholdConsolidationMobileHhRevAllRoute,
    HouseholdConsolidationMobileHhRevBbRoute:
      HouseholdConsolidationMobileHhRevBbRoute,
  }

const HouseholdConsolidationMobileHhRouteRouteWithChildren =
  HouseholdConsolidationMobileHhRouteRoute._addFileChildren(
    HouseholdConsolidationMobileHhRouteRouteChildren,
  )

interface HouseholdRouteChildren {
  HouseholdConsolidationMobileHhRouteRoute: typeof HouseholdConsolidationMobileHhRouteRouteWithChildren
  HouseholdDemandsDeploymentRoute: typeof HouseholdDemandsDeploymentRoute
  HouseholdRevenueC3mrRoute: typeof HouseholdRevenueC3mrRoute
  HouseholdSalesFulfilmentRoute: typeof HouseholdSalesFulfilmentRoute
}

const HouseholdRouteChildren: HouseholdRouteChildren = {
  HouseholdConsolidationMobileHhRouteRoute:
    HouseholdConsolidationMobileHhRouteRouteWithChildren,
  HouseholdDemandsDeploymentRoute: HouseholdDemandsDeploymentRoute,
  HouseholdRevenueC3mrRoute: HouseholdRevenueC3mrRoute,
  HouseholdSalesFulfilmentRoute: HouseholdSalesFulfilmentRoute,
}

const HouseholdRouteWithChildren = HouseholdRoute._addFileChildren(
  HouseholdRouteChildren,
)

interface PumaRouteChildren {
  PumaPayingSubsRoute: typeof PumaPayingSubsRoute
  PumaRevenueByuRoute: typeof PumaRevenueByuRoute
  PumaRevenueCvmRoute: typeof PumaRevenueCvmRoute
  PumaRevenueCvmOutletRoute: typeof PumaRevenueCvmOutletRoute
  PumaRevenueGrossRoute: typeof PumaRevenueGrossRoute
  PumaRevenueGrossPrabayarRoute: typeof PumaRevenueGrossPrabayarRoute
  PumaRevenueNewSalesRoute: typeof PumaRevenueNewSalesRoute
  PumaRevenueNewSalesPrabayarRoute: typeof PumaRevenueNewSalesPrabayarRoute
  PumaRevenueRedeemPvRoute: typeof PumaRevenueRedeemPvRoute
  PumaTargetSoRoute: typeof PumaTargetSoRoute
  PumaTrxNewSalesRoute: typeof PumaTrxNewSalesRoute
  PumaTrxNewSalesByuRoute: typeof PumaTrxNewSalesByuRoute
  PumaTrxNewSalesPrabayarRoute: typeof PumaTrxNewSalesPrabayarRoute
}

const PumaRouteChildren: PumaRouteChildren = {
  PumaPayingSubsRoute: PumaPayingSubsRoute,
  PumaRevenueByuRoute: PumaRevenueByuRoute,
  PumaRevenueCvmRoute: PumaRevenueCvmRoute,
  PumaRevenueCvmOutletRoute: PumaRevenueCvmOutletRoute,
  PumaRevenueGrossRoute: PumaRevenueGrossRoute,
  PumaRevenueGrossPrabayarRoute: PumaRevenueGrossPrabayarRoute,
  PumaRevenueNewSalesRoute: PumaRevenueNewSalesRoute,
  PumaRevenueNewSalesPrabayarRoute: PumaRevenueNewSalesPrabayarRoute,
  PumaRevenueRedeemPvRoute: PumaRevenueRedeemPvRoute,
  PumaTargetSoRoute: PumaTargetSoRoute,
  PumaTrxNewSalesRoute: PumaTrxNewSalesRoute,
  PumaTrxNewSalesByuRoute: PumaTrxNewSalesByuRoute,
  PumaTrxNewSalesPrabayarRoute: PumaTrxNewSalesPrabayarRoute,
}

const PumaRouteWithChildren = PumaRoute._addFileChildren(PumaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignRoute: CampaignRouteWithChildren,
  HouseholdRoute: HouseholdRouteWithChildren,
  LoginRoute: LoginRoute,
  PumaRoute: PumaRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
